### ISSUE TITLE
Conflicts with alpha-nvim

### ISSUE THREAD

**Issue by loqusion** [tummetott/reticle.nvim#4] opened 2023-09-07 23:04 UTC
When `alpha-nvim` is used as dashboard, `cursorline` is not set when opening a file with `telescope.nvim` or `neo-tree.nvim`. This behavior persists even when `"alpha"` is added to `opts.ignore.cursorline` or `opts.never.cursorline`.

![2023-09-07_18-03-03](https://github.com/tummetott/reticle.nvim/assets/38332081/ee26da50-4706-4a3e-955b-e4354b076a17)

**Comment by loqusion** [comment] 2023-09-07 23:06
(Duplicate of #2?)

**Comment by tummetott** [comment] 2023-09-11 10:09
Yes it's basically the same problem like in issue #1
I'll fix that very soon. Thanks for reporting

**Comment by tummetott** [comment] 2023-10-17 11:50
The issue is addressed in the latest commit. Please take note that the plugin no longer recognizes the cursorline or cursorline state that was configured using `vim.opt.cursorline = true`, and instead, refer to the README for instructions on using the user-exposed functions to manage the cursorline. If you wish to enable the cursorline on startup, you can set the `opts.on_startup.cursorline` option to true.

**Closed as completed by tummetott** 2023-10-17 11:50 UTC
